name: icme3.10-cuda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=12.4
  - cudnn=9.1
  - hdf5        # optional but helps h5py performance
  - libopenblas # optional; remove if you prefer MKL/Accelerate
  - cx_oracle=8.3.0=py310h7bdd564_5
  - psycopg=3.3.2=pyh848bd53_0
  - psycopg-c=3.3.2=py310h9c59733_0
  - pip:
      # Deep learning (CUDA)
      - tensorflow==2.16.2
      - nvidia-cudnn-cu12==8.9.4.25
      - jax==0.4.34
      - jaxlib==0.4.34+cuda12.cudnn89

      # Core numerics / imaging
      - numpy==1.26.4
      - pandas==2.3.3
      - scipy==1.15.3
      - scikit-image==0.25.2
      - pillow==12.0.0
      - matplotlib==3.10.7
      - matplotlib-venn==1.1.2
      - seaborn==0.13.2
      - mahotas==1.4.18
      - h5py==3.15.1
      - tqdm==4.67.1
      - sympy==1.14.0
      - xarray==2025.6.1

      # Solar / space physics
      - sunpy==6.0.6
      - astropy==6.1.7
      - drms==0.9.0
      - reproject==0.14.1
      - aiapy==0.10.2
      - spacepy==0.7.0
      - cdasws==1.8.12
      - cdflib==1.3.7
      - pyspedas==2.0.5

      # Notebooks / viz
      - jupyterlab==4.5.0
      - ipykernel==7.1.0
      - ipywidgets==8.1.8
      - plotly==6.5.0

      # IO / misc
      - beautifulsoup4==4.14.3
      - botocore==1.40.61
      - imageio==2.37.2
      - lxml==6.0.2
      - pyarrow==22.0.0
      - rich==14.2.0
      - requests>=2.32
