name: icme3.10-nn-metal
channels:
  - conda-forge
  - apple
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cx_oracle=8.3.0=py310h7bdd564_5
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - hdf5=1.14.6=nompi_hd3baa01_104
  - icu=75.1=hfee45f7_0
  - krb5=1.21.3=h237132a_0
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libblas=3.11.0=4_h51639a9_openblas
  - libcblas=3.11.0=4_hb0561ab_openblas
  - libcurl=8.17.0=hdece5d2_0
  - libcxx=21.1.7=hf598326_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.3=haf25636_0
  - libffi=3.5.2=he5f378a_0
  - libgcc=15.2.0=hcbb3090_15
  - libgfortran=15.2.0=h07b0088_15
  - libgfortran5=15.2.0=hdae7583_15
  - libgrpc=1.74.1=h3063b79_1
  - liblapack=3.11.0=4_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpq=18.1=h944245b_2
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.11.05=h91c62da_0
  - libsqlite=3.51.1=h9a5124b_0
  - libssh2=1.11.1=h1590b86_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.7=h4a912ad_0
  - ncurses=6.5=h5e97a16_3
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - psycopg=3.3.2=pyh848bd53_0
  - psycopg-c=3.3.2=py310h9c59733_0
  - python=3.10.19=hcd7f573_2_cpython
  - python_abi=3.10=8_cp310
  - re2=2025.11.05=h64b956e_0
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tensorflow-deps=2.9.0=0
  - tk=8.6.13=h892fb3f_3
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hbf9d68e_6
  - pip:
      - absl-py==2.3.1
      - aiapy==0.10.2
      - aioboto3==15.5.0
      - aiobotocore==2.25.1
      - aiofiles==25.1.0
      - aioftp==0.27.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - anyio==4.12.0
      - appnope==0.1.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asciitree==0.3.3
      - astropy==6.1.7
      - astropy-healpix==1.1.2
      - astropy-iers-data==0.2025.12.1.0.45.12
      - asttokens==3.0.1
      - astunparse==1.6.3
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - boto3==1.40.61
      - botocore==1.40.61
      - cached-property==2.0.1
      - cdasws==1.8.12
      - cdflib==1.3.7
      - certifi==2025.11.12
      - cffi==2.0.0
      - cftime==1.6.5
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - dask==2025.11.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - drms==0.9.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - flatbuffers==25.9.23
      - fonttools==4.61.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gast==0.7.0
      - geopack==1.0.12
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hapiclient==0.2.6
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - ipykernel==7.1.0
      - ipympl==0.9.8
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isodate==0.7.2
      - isoduration==20.11.0
      - jax==0.4.34
      - jax-metal==0.1.1
      - jaxlib==0.4.34
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - keras==3.12.0
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - libclang==18.1.1
      - locket==1.0.0
      - lxml==6.0.2
      - mahotas==1.4.18
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - matplotlib-venn==1.1.2
      - mdurl==0.1.2
      - mistune==3.1.4
      - ml-dtypes==0.3.2
      - mpl-animators==1.2.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - namex==0.1.0
      - narwhals==2.13.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - netcdf4==1.7.3
      - networkx==3.4.2
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - numcodecs==0.13.1
      - numpy==1.26.4
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optree==0.18.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parfive==2.2.0
      - parso==0.8.5
      - partd==1.4.2
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - plotly==6.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==4.25.8
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pycparser==2.23
      - pyerfa==2.0.1.5
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyspedas==2.0.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - reproject==0.14.1
      - requests==2.32.5
      - requests-file==3.0.1
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - s3fs==2025.12.0
      - s3transfer==0.14.0
      - scikit-image==0.25.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - spacepy==0.7.0
      - stack-data==0.6.3
      - sunpy==6.0.6
      - sympy==1.14.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-macos==2.16.2
      - tensorflow-metal==1.2.0
      - termcolor==3.2.0
      - terminado==0.18.1
      - tifffile==2025.5.10
      - tinycss2==1.4.0
      - tomli==2.3.0
      - toolz==1.1.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.6.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - wrapt==1.17.3
      - xarray==2025.6.1
      - yarl==1.22.0
      - zarr==2.18.3
      - zeep==4.3.2
      - zipp==3.23.0
prefix: /Users/aosh/anaconda3/envs/icme3.10-nn-metal
