name: icme3.12-cuda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - hdf5
  - h5py
  - pip:
      # Deep learning (CUDA runtime via pip wheels)
      - tensorflow[and-cuda]==2.19.1
      # - nvidia-cudnn-cu12
      # - nvidia-cublas-cu12<=12.2
      # - nvidia-cuda-runtime-cu12<=12.2
      
      # - keras==3.12.0
      # - jax==0.4.34
      # - jaxlib==0.4.34

      # Core numerics / imaging
      - numpy
      - pandas
      - scipy
      - scikit-image
      - pillow
      - matplotlib
      - matplotlib-venn
      - seaborn
      - mahotas
      - tqdm
      - dtaidistance
      - sympy
      - xarray

      # Solar / space physics
      - sunpy
      - astropy
      - drms
      - reproject
      - aiapy

      # Notebooks / viz
      - jupyterlab
      - ipykernel
      - ipywidgets
      - plotly

      # IO / misc
      - beautifulsoup4
      - botocore
      - protobuf==4.25.8
      - cdasws
      - cdflib
      - imageio
      - lxml=6.0.2
      - pyspedas
      - pytplot-mpl-temp>=2.1.17
      - spacepy=0.7.0
      - pyarrow=22.0.0
      - rich
      - openpyxl
      - requests
      - psycopg
      - cx_Oracle
