name: icme3.12-metal
channels:
  - apple
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - hdf5
  - h5py
  - pip:
      # Deep learning
      - tensorflow==2.19.1
      - tensorflow-metal==1.2.0
      # - keras==3.12.0
      # - jax==0.4.34
      # - jaxlib==0.4.34
      # - jax-metal==0.1.1

      # Core numerics / imaging
      - numpy
      - pandas
      - scipy
      - scikit-image
      - pillow
      - matplotlib
      - matplotlib-venn
      - seaborn
      - mahotas
      - tqdm
      - dtaidistance
      - sympy
      - xarray

      # Solar / space physics
      - sunpy
      - astropy
      - drms
      - reproject
      - aiapy

      # Notebooks / viz
      - jupyterlab
      - ipykernel
      - ipywidgets
      - plotly

      # IO / misc
      - beautifulsoup4
      - botocore
      - protobuf==4.25.8
      - cdasws
      - cdflib
      - imageio
      - lxml=6.0.2
      - pyspedas
      - pytplot-mpl-temp>=2.1.17
      - spacepy=0.7.0
      - pyarrow=22.0.0
      - rich
      - openpyxl
      - requests
      - psycopg
      - cx_Oracle
