name: icme3.10-cuda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - hdf5 # optional but helps h5py performance
  - libopenblas # optional; remove if you prefer MKL/Accelerate
  - cx_oracle
  - psycopg
  - psycopg-c
  - pip:
      # Deep learning (CUDA)
      - tensorflow==2.16.2
      - keras==3.12.0
      - jax[cuda12]==0.4.34
      - jaxlib[cuda12]==0.4.34
      
      # Core numerics / imaging
      - numpy
      - pandas
      - scipy
      - scikit-image
      - pillow
      - matplotlib
      - matplotlib-venn
      - seaborn
      - mahotas
      - h5py
      - tqdm
      - sympy
      - xarray

      # Solar / space physics
      - sunpy
      - astropy
      - drms
      - reproject
      - aiapy
      - spacepy
      - cdasws
      - cdflib
      - pyspedas

      # Notebooks / viz
      - jupyterlab
      - ipykernel
      - ipywidgets
      - plotly

      # IO / misc
      - beautifulsoup4
      - botocore
      - imageio
      - lxml
      - pyarrow
      - rich
      - requests
