name: icme3.12-cuda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - hdf5
  - pip:
      # Deep learning (CUDA runtime via pip wheels)
      - tensorflow==2.19.1
      - nvidia-cudnn-cu12==9.1.1.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-runtime-cu12==12.4.127
      # - keras==3.12.0
      # - jax==0.4.34
      # - jaxlib==0.4.34

      # Core numerics / imaging
      - numpy
      - pandas
      - scipy
      - scikit-image
      - pillow
      - matplotlib
      - matplotlib-venn
      - seaborn
      - mahotas
      - h5py
      - tqdm
      - sympy
      - xarray

      # Solar / space physics
      - sunpy
      - astropy
      - drms
      - reproject
      - aiapy

      # Notebooks / viz
      - jupyterlab
      - ipykernel
      - ipywidgets
      - plotly

      # IO / misc
      - beautifulsoup4
      - botocore
      - protobuf==4.25.8
      - cdasws
      - cdflib
      - imageio
      - lxml
      - pyspedas
      - spacepy
      - pyarrow
      - rich
      - requests
      - psycopg
      - cx_Oracle
